# 1. Diz ao Spring para criar um arquivo de banco de dados chamado "campeonatos.db" na raiz do projeto
spring.datasource.url=jdbc:sqlite:campeonatos.db

# 2. Informa qual é o driver do banco
spring.datasource.driver-class-name=org.sqlite.JDBC

# 3. A SOLUÇÃO DO SEU ERRO: Informa o endereço correto do Dialeto na versão nova do Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 4. A MÁGICA: Diz ao Spring para ler as suas classes @Entity e criar as tabelas no SQLite sozinho!
spring.jpa.hibernate.ddl-auto=update

# 5. Opcional: Mostra no console os comandos SQL que o Spring está executando nos bastidores
spring.jpa.show-sql=true